# Generated by Django 2.2.6 on 2019-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('priv', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='privilege',
            options={'ordering': ['priv']},
        ),
    ]
